baseURL: "https://Shivamchhetry20.github.com"
title: Shivam Chhetry
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

outputs:
     home:
         - HTML
         - RSS
         - JSON
menu:
    main:
        - name: Books
          url: books/
          weight: 5
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6
        - name: Search
          url: search/
          weight: 6

params:
    description: "I'm a Data Scientist with a passion for exploring AI models and pushing the boundaries of technology. I started coding early on, which sparked my journey into Computer Science. After earning my Bachelor's degree, I've spent the past year diving deep into Data Science and Machine Learning in the tech sector. I'm passionate about sharing my technical insights and love solving complex challenges with innovative ideas. Inspired by the Japanese concept of Kata, I believe in thoughtful, continuous improvement and driving impactful innovation."
    author: Shivam Chhetry
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: <span style="color:#011F5B">Shivam Chhetry</span>
          imageUrl: "profile.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Blogs
              url: papers/
            - name: Projects
              url: courses/
            # - name: Data
            #   url: data/
            - name: Books
              url: books/
            - name: Tags
              url: tags/
            - name: Research-Paper
              url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          subtitle: I'm a **Data Scientist** at <span style="color:#ff6600">**[Apollo Hospital Center](https://www.apollohospitals.com/bangalore/best-hospital-in-bannerghatta-road/)**</span> specializing in **AI and Deep Learning for healthcare** 🚀. My work focuses on analyzing **Microbiology Lab health records** to identify antibiotic-resistant organisms 🦠 and their impact on patient outcomes.<br><br>With expertise in **Machine Learning, Deep Learning, Python 🐍, and PyTorch 🔥**, I build scalable AI solutions that bridge the gap between technology and real-world applications. I thrive on solving complex problems, optimizing workflows, and driving **AI-driven innovation.** 💡<br><br> I am actively seeking opportunities to apply my skills in **cutting-edge AI research and impactful data-driven solutions**.

    socialIcons:
        - name: Resume
          url: cv.pdf
        - name: Email
          url: mailto:moritz.maria.von.igelfeld@gmail.com
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Medium
          url: https://pmichaillat.substack.com
        - name: Kaggle
          url: https://www.youtube.com/@alexandermccallsmithoffici9000
        - name: Linkedin
          url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Shivam Chhetry"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
